# HTTP 代理端口
port: 2001

# SOCKS5 代理端口
socks-port: 2002

# HTTP(S) and SOCKS4(A)/SOCKS5 server on the same port
mixed-port: 2003

# 允许局域网的连接（可用来共享代理）
allow-lan: true

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / error / warning / info / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info

# Clash 的 RESTful API
external-controller: "0.0.0.0:${PORT_clash}"

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# http://127.0.0.1:9090/ui/#/
# external-ui: folder
# yacd面板：  https://github.com/haishanh/yacd
# Razord面板：http://clash.razord.top/#/proxies
external-ui: dashboard

# RESTful API 的口令 (可选)
secret: "0000"

#dns:
  #enable: true # 是否启用dns false
  #ipv6: false
  #listen: 0.0.0.0:53
  #enhanced-mode: redir-host # 模式：redir-host或fake-ip
  #fake-ip-range: 198.18.0.1/16 #
  #fake-ip-filter: # fake ip 白名单列表，如果你不知道这个参数的作用，请勿修改
     #- '*.lan'
     #- localhost.ptlogin2.qq.com
  #nameserver:
     #- 223.5.5.5 # 阿里DNS
     #- 180.76.76.76 # 百度DNS
     #- 119.29.29.29 # 腾讯DNS
     #- 117.50.11.11 # ONE DNS拦截版 恶意网站拦截、广告过滤
     #- 117.50.10.10 # ONE DNS纯净版 直接返回其真实的响应结果
     #- 114.114.114.114 # 114DNS
  #fallback:
     #- 8.8.8.8 # 谷歌DNS
     #- 1.1.1.1 # Cloudflare DNS
     #- tls://dns.rubyfish.cn:853
     #- tls://1.0.0.1:853
     #- tls://dns.google:853
     #- https://dns.rubyfish.cn/dns-query
     #- https://cloudflare-dns.com/dns-query
     #- https://dns.google/dns-query
  #fallback-filter:
     #geoip: true # 默认
     #ipcidr: # 在这个网段内的 IP 地址会被考虑为被污染的 IP
       #- 240.0.0.0/4


# Clash for Windows
# Proxies module latency test settings
cfw-latency-timeout: 3000
cfw-latency-url: http://www.gstatic.com/generate_204

# 打断连接
# Identify strategy of breaking connections after switching to a new proxy/profile/mode
# Options for proxy: none, chain(proxy group in connection chains), all
# Options for profile: true, false
# Options for mode: true, false
cfw-conn-break-strategy:
  proxy: none # none/chain/all
  profile: true # true/false
  mode: false # true/false

